---
kind: ReplicationController
apiVersion: v1
metadata:
  name: guestbook
  labels:
    app: guestbook
spec:
  replicas: 3
  selector:
    app: guestbook
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
      - name: guestbook
        image: 122734987158.dkr.ecr.us-east-1.amazonaws.com/guestbook-go:v58
        ports:
        - name: http-server
          containerPort: 3000
